---
# ------ Training settings
logging_dir: 'training_logs/' # Directory to save weights and such
input_size: 128 # Input images are resized to this square HxW size
batch_size: 32 # Training batch size
epochs: 50 # Number of training epochs

# ------ Dataset/weights paths
landmarks_dir: '/path/to/landmarks/image/directory/' # directory of images numbered sequentially, each corresponding to a landmark
exclude_indices: '' # None or path to pickle array with landmark indices that should be in test set
pretrained_weights: '' # None or path to pretrained weights ckpt (for continued training)

# ------ Model settings
mars_enabled: True # Set to false to disable MARs (and use Metric Learning alone)
channel_gamma: 0.15 # MARs channel alignment weight, default 0.15
spatial_gamma: 0.15 # MARs spatial alignment weight, default 0.15
conv_type: 'ric' # Convolution type, 'conv' = conv2d, 'ric' = rotation-invariant convolution
att_type: 'ca' # Attention type, 'se' = squeeze-excitation, 'ca' = coordinate attention
metric_learning_loss: 'proxyanchor' # [proxyanchor, proxynca++, subcenterarcface, synproxy, ntxent, drms, supcon, circle, pnp, multisim]

# ------ Evaluation settings
eval: False # Perform paper 'Recall@1' and 'Incremental Recall@1' on 'landmarks_dir' above
luna1_eval: False # Perform paper 'Moon Navigation' and 'Moon Lost-in-Space' with Luna-1 dataset
luna1_annotation_file: '/path/to/luna1/lro_navigation/annotations.txt'
