---
# ------ Training settings
logging_dir: './logs/' # where to save model checkpoints and such
input_size: 128 # Input images are resized to this square HxW size
batch_size: 128 # Training batch size
epochs: 150 # Number of training epochs

# ------ Dataset/weights paths
landmarks_dir: 'path/to/directory/of/luna-1/craters/'
exclude_indices: None # None or path to pickle array with landmark indices that should be in test set
pretrained_weights: None # None or path to pretrained weights ckpt (for continued training)

# ------ Model settings
mars_enabled: True
channel_gamma: 0.15 # MARs channel alignment weight
spatial_gamma: 0.15 # MARs spatial alignment weight
conv_type: 'ric' # Convolution type, 'conv' = conv2d, 'ric' = rotation-invariant convolution
att_type: 'ca' # Attention type, 'se' = squeeze-excitation, 'ca' = coordinate attention
metric_learning_loss: 'proxyanchor' # [proxyanchor, proxynca++, subcenterarcface, synproxy, ntxent, drms, supcon, circle, pnp, multisim]

# ------ Evaluation settings
eval: True # Perform paper 'Recall@1' and 'Incremental Recall@1' on 'landmarks_dir' above
luna1_eval: True # Perform paper 'Moon Navigation' and 'Moon Lost-in-Space' with Luna-1 dataset
luna1_annotation_file: /path/to/luna-1/lro_navigation/annotations.txt
